source 'https://rubygems.org'

gem 'rails'
gem 'therubyracer', platforms: :ruby
gem 'turbolinks'
gem 'jbuilder'
gem 'thin'
gem 'responders'
gem 'omniauth'

group :development, :test do
  gem 'better_errors'
  gem 'sqlite3'
  gem 'pry-rails'
end

group :development do
  gem 'rails-env'
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-bundler'
  gem 'foreman'
end

group :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'database_cleaner'
end

group :staging, :production do
  gem 'mysql'
end

group :production do
  gem 'rails_12factor'
end
